# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# If for any reason this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve', please restart the server process.

# Site settings
title: 'Otvoreni proračun'

email: openzagreb@codeforcroatia.org

description: ''

# the subpath of your site, e.g. /blog
baseurl: ''

# the base hostname & protocol for your site, e.g. http://example.com
url: 'https://dev.proracun.org'

# set the default language
default_lang: hr

site_logo: 'ohh-logo.svg'
analytics:
  enable: false
  google_analytics:
    enable: false
    code: ""
  piwik:
    enable: false
    tracking_pixel_uri: "/piwik.okfn.de/piwik.php?idsite=4"
    link_tracking: "//traffic.okfn.de/"
footerGdprMessage: false

twitter_username: openzagreb
github_username: openzagreb
github_repo: proracun
foia_url: 'https://imamopravoznati.org/'

# Haushalte
collections:
  os_config:
    output: true
  budget:
    output: true
    permalink: /proracun/:name/
  haushalte:
    output: true
    permalink: /prikaz/:name/
  haushalte:
    output: true
    permalink: /prikaz/:path/
  haushalte-edit:
    output: true
    permalink: /prikaz/:name/edit
  embed:
    output: true
    permalink: /prikaz/:name/embed
  embed-full:
    output: true
    permalink: /prikaz/:name/embed-full


# Build settings
markdown: kramdown
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - bower.json
  - bower_components/*
sass:
  sass_dir: static/css/_scss
  style: compressed

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: page
    values:
      layout: page
      framed: true
  -
    scope:
      path: "_budget"
      type: budget
    values:
      layout: budget
  -
    scope:
      path: "_haushalte"
      type: haushalte
    values:
      layout: budget2
  -
    scope:
      path: "_haushalte-edit"
      type: haushalte-edit
    values:
      layout: budget-edit
  -
    scope:
      path: "_embed"
    values:
      layout: embed
  -
    scope:
      path: "_embed-full"
    values:
      layout: embed-full
#
#
#
# We use the embed plugin here to generate the same pages
# with the embed layout again
